name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build frontent
        run: |
          docker build ./client/ -t jeelp/bugvilla_frontend
      - name: docker build backend
        run: |
          docker build ./ -t jeelp/bugvilla_backend
      
      - name: docker push
        run: |
          docker push jeelp/bugvilla_frontend
          docker push jeelp/bugvilla_backend
        
      
      
          
          
          
  
      
