name: Docker CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build
        run: |
          docker build ./ -t jeelp/bugvilla

      - name: docker push
        run: |
          docker push jeelp/bugvilla
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:  
      - name: Deploy to Vultr VPS via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }} 
          port: 22
          script: |
            echo ${{ secrets.DB_CONNECT_ATLAS }}
            docker stop bugvilla
            docker pull jeelp/bugvilla
            docker run -d -e NODE_ENV="production" -e DB_CONNECT_ATLAS="${{ secrets.DB_CONNECT_ATLAS }}" -e TOKEN_SECRET="${{ secrets.TOKEN_SECRET }}" -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" -e SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}" -e EXPIRATION_TIME="${{ secrets.EXPIRATION_TIME }}" -p 5000:5000 jeelp/bugvilla 
            
